#!/usr/bin/newlisp


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;;	Test functions
;

(load "article.lsp")
(context MAIN)

(auxiliary:open-database (nth 2 (main-args)))

(println "\nFunctions for category manipulation:")
(println "\tAdd category . . . . 11")
(println "\tEdit category. . . . 12")
(println "\tRemove category. . . 13")
(println "\tShow category info . 14")
(println "\tShow all categories. 15")

(println "\nFunctions for article manipulation:")
(println "\tAdd article. . . . . 21")
(println "\tEdit article . . . . 22")
(println "\tRemove article . . . 23")
(println "\tShow article . . . . 24")
(println "\tShow all articles. . 26")
(println "\tToggle featured. . . 27")

(println "\t----------------------")
(println "\tClose. . . . . . . . 0")

(print "Option: ")
(set 'menu-option (read-line))
(until (= menu-option "0")
	(when (= menu-option "11")	
		(print "\nEnter category name: ")
		(set 'name (read-line))
		(print "Enter category parent int: ")
		(set 'parent (read-line))
		(print "Enter category description: ")
		(set 'description (read-line))
		(category:create name parent description))
	(when (= menu-option "12")
		(print "\nEnter category ID: ")
		(set 'id (read-line))
		(print "Enter new title: ")
		(set 'new-name (read-line))
		(print "Enter new description: ")
		(set 'new-description (read-line))
		(category:update id new-name new-description))
	(when (= menu-option "13")
		(print "\nEnter category ID: ")
		(set 'id (read-line))
		(category:remove id))
	(when (= menu-option "14")
		(print "\nEnter category key (ID, name or slug): ")
		(set 'key (read-line))
		(print "Enter key value: ")
		(set 'value (read-line))
		(category:show key value))
	(when (= menu-option "15")
		(category:show-all))

	(when (= menu-option "21")	
		(print "\nEnter article title: ")
		(set 'article-title (read-line))
		(print "Enter article category: ")
		(set 'article-category (read-line))
		(print "Is article featured? [y/n]: ")
		(set 'article-featured (read-line))
		(print "Enter content of article: ")
		(set 'article-content (read-line))
		(article:create article-title article-category article-featured article-content))
	(when (= menu-option "22")
		(print "\nEnter article ID: ")
		(set 'id (read-line))
		(print "Enter new title: ")
		(set 'new-name (read-line))
		(print "Enter new content: ")
		(set 'new-content (read-line))
		(article:update id new-name new-content))
	(when (= menu-option "23")
		(print "\nEnter article ID: ")
		(set 'id (read-line))
		(article:remove id))
	(when (= menu-option "24")	
		(print "\nEnter article key (ID, name or slug): ")
		(set 'key (read-line))
		(print "Enter key value: ")
		(set 'value (read-line))
		(article:show key value))
	(when (= menu-option "26")	
		(article:show-all))
	(when (= menu-option "27")
		(print "\nEnter article ID: ")
		(set 'id (read-line))
		(article:featured id))
	(print "Option: ")
	(set 'menu-option (read-line)))

(auxiliary:close-database)

(exit)
